changelog:
  exclude:
    labels:
      - docs
      - chore
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📦 Dependencies
      labels:
        - dependency
    - title: 🔧 Internal
      labels:
        - ci
        - infra